# Generated by Django 3.1.7 on 2021-03-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210304_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='use_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='use_screenshots',
        ),
        migrations.AddField(
            model_name='project',
            name='alt_text1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='caption1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='caption2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='caption3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='caption4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
