# Generated by Django 3.1.7 on 2021-03-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210304_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt_text_main',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
